Update ImporterContext.cs
vrm-c/UniVRM pull request #1121
Opened 2021-08-02 01:25 UTC by StephenHodgson

fix `This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.`

2021-08-02 10:29 UTC, Santarh approved these changes
LGTM !

2021-08-02 10:43 UTC, Santarh requested changes
Sorry.
This fix cause a compile error.

2021-08-02 12:35 UTC, StephenHodgson commented
Really? Okay I'll check it out again.

2021-08-02 13:08 UTC, StephenHodgson commented
@Santarh what exactly is the compile error? I'm not seeing it on my end.

2021-08-03 07:36 UTC, Santarh commented
@StephenHodgson Compile errors in Unity 2018.4 are shown below.
This lambda expression should return `Task<AnimationClip>` instead of `AnimationClip` .

```
Assets\UniGLTF\Runtime\UniGLTF\IO\ImporterContext.cs(128,32): error CS0029: Cannot implicitly convert type 'UnityEngine.AnimationClip' to 'System.Threading.Tasks.Task<UnityEngine.AnimationClip>'

Assets\UniGLTF\Runtime\UniGLTF\IO\ImporterContext.cs(128,32): error CS1662: Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type

```

2021-08-03 13:14 UTC, StephenHodgson commented
Hmm seems like there must be a mismatched dependency somehow.

When just pulling in the upm package from openupm it complains that the task will run synchronously because the method does not return a task but you're saying it actually returns a task in your version.

I'll just close this.

2021-08-03 13:14 UTC, closed without merging