未知の material をエクスポートするとエラーになるのを回避
vrm-c/UniVRM pull request #1385
Opened 2021-11-24 11:15 UTC by ousttrue

2021-11-24 12:19 UTC, ousttrue commented
たとえば vrm を gltf としてエクスポートしようとするとヒットする・・・

2021-11-25 06:20 UTC, Santarh requested changes

2021-11-25 06:20 UTC, Santarh commented on Assets/UniGLTF/Editor/UniGLTF/ExportDialog/MaterialValidator.cs
> +            if (GetGltfMaterialTypeFromUnityShaderName(m.shader.name) == "Standard")
Standard 互換のシェーダが Standard として認識されなくなる副作用がありそう

2021-11-25 06:23 UTC, Santarh approved these changes
よさそう

2021-11-25 06:24 UTC, merged