[1.0] ScriptableObject VRM10Expression の値域を 0-1 に修正
vrm-c/UniVRM pull request #1387
Opened 2021-11-24 12:18 UTC by ousttrue

#1380

値域が 0-100 だったので import/export 時に値域の操作が必用だった
値域を 0-1 に修正

* GetBlendShapeWeight 時に 0.01 倍する
* SetBlendShapeWeight 時に 100 倍する
* それ以外で操作しない

ように修正。

2021-11-24 12:33 UTC, Santarh requested changes
よさそう。何点か

2021-11-24 12:33 UTC, Santarh commented on Assets/VRM10/Editor/Components/Expression/ExpressionEditorHelper.cs
> +            var newValue = EditorGUI.Slider(rect, prop.floatValue, 0, maxValue);
考慮漏れ

2021-11-24 12:33 UTC, Santarh commented on Assets/VRM10/Editor/Components/Expression/SerializedExpressionEditor.cs
> +                            var src = renderer.GetBlendShapeWeight(i) * 0.01f;
「Unity のウェイトをノーマライズする係数」という名前の const float にしたほうが（未来にコードを見る時に）分かりやすい気がします。
`const float UnityBlendshapeWeightNormalizeCoef = 0.01f;` とか

2021-11-24 12:33 UTC, Santarh commented on Assets/VRM10/Editor/EditorTool/VRM10ExpressionEditorTool.cs
> +            var root = Selection.activeTransform?.GetComponent<Vrm10Instance>();
`UnityEngine.Object` に対する `?.` って有効な操作になったっけ…？

2021-11-24 12:33 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Expression/MorphTargetBinding.cs
> +                Debug.LogWarning($"weight exceed 1.0");
よさそう

2021-11-24 12:33 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Expression/MorphTargetBindingMerger.cs
> +                                    target.SetBlendShapeWeight(binding.Index, x * 100.0f);
こちらも
`const float GltfBlendshapeWeightToUnityBLendshapeWeightCoef = 100f;`
とか（もっとも冗長ネーミング）

2021-11-24 12:36 UTC, ousttrue commented on Assets/VRM10/Editor/EditorTool/VRM10ExpressionEditorTool.cs
> +            var root = Selection.activeTransform?.GetComponent<Vrm10Instance>();
たしかに・・・

2021-11-25 06:05 UTC, Santarh approved these changes
よさそう。

2021-11-25 06:05 UTC, Santarh commented on Assets/VRM10/Editor/Components/Expression/SerializedExpressionEditor.cs
> +                        var unityWeight = x.SkinnedMeshRenderer.GetBlendShapeWeight(i);
👍

2021-11-25 06:05 UTC, Santarh commented on Assets/VRM10/Editor/Components/Expression/ReorderableMorphTargetBindingList.cs
> +                if (ExpressionEditorHelper.FloatSlider(rect, property.FindPropertyRelative(nameof(MorphTargetBinding.Weight)), MorphTargetBinding.MAX_WEIGHT))
👍

2021-11-25 06:05 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Expression/MorphTargetBinding.cs
> +
👍

2021-11-25 06:07 UTC, merged