Fix/use native array
vrm-c/UniVRM pull request #1483
Opened 2022-01-25 11:06 UTC by ousttrue

GltfData.Bin の型を ArraySegment<byte> から NativeArray<byte> に変更しました。
それに伴って、GltfData.Dispose の呼び出しが必要になりました。
一般的なランタイムロードを簡略化する高レベルAPI

* GltfUtility
* VrmUtility

を追加しました。
`1.0` 向けは次回以降に実装予定です。

2022-01-25 11:07 UTC, ousttrue commented on Assets/UniGLTF/Runtime/UniGLTF/IO/AnimationIO/AnimationImporterUtil.cs
> +                                input.ToArray(),
次回以降最適化するかも。とりあえず ToArray

2022-01-25 11:09 UTC, ousttrue commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +
GltfData.Dispose で Diseose される NativeArray を作成する Factory。
GltfData関連では、自分で new せずにこれを使うことで Dispose を任せられる。

2022-01-25 11:50 UTC, Santarh requested changes
方針はヨシ。

何点か気になりポイント。

HLAPI はちょっと自分でもインタフェースを考えてみます。

2022-01-25 11:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/AnimationIO/AnimationImporterUtil.cs
> +                                input.ToArray(),
`SetAnimationCurve` の実装を見る限りは readonly っぽいのでできそうですね。まあ次の PR で。

2022-01-25 11:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +    public sealed class GltfData : IDisposable
👍

2022-01-25 11:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +        public NativeArray<byte>? _bin;
private の間違い？

2022-01-25 11:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +                            _bin = CreateNativeArray(Chunks[1].Bytes);
コンストラクタで生成してしまって不都合はないように思えますが、どうだろう？

2022-01-25 11:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +                data = CreateNativeArray(UriByteBuffer.ReadEmbedded(uri));
なるほど、base64 などのリソースだとたしかに新たに NativeArray を作る必要がそりゃあるか。

2022-01-25 11:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +        List<IDisposable> m_disposables = new List<IDisposable>();
フィールド変数は上の方に `_storage` などと同じ位置に固めてもらったほうがありがたいですね（正直さがしづらいので）

2022-01-25 11:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +        public void Dispose()
Dispose の定義はコンストラクタの次に書いてあったほうが見やすい気持ちがあります

2022-01-25 11:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfUtility.cs
> +    public static class GltfUtility
HLAPI いいですね。
この辺の命名はのちに asmdef の整理とともにいい感じのを探りたいです。

2022-01-25 11:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +
glTF と Unity で概念が違う以上、Importer のコンテキストで新たにバッファを作る必要は必ずある。
そこそこ便利にそこそこ綺麗にその処理を押し込める手法として、ちょうどよさそう。

2022-01-25 11:50 UTC, Santarh commented on Assets/UniGLTF/Tests/UniGLTF/EditorTextureSerializerTests.cs
> +            using (var parsed = GltfData.CreateFromGltfDataForTest(gltf, data.BinBytes))
👍

2022-01-25 11:50 UTC, Santarh commented on Assets/VRM10/Runtime/IO/Vrm10Data.cs
> +            using (data)
うーんなるほど、このあたりの API 眺めてみたけど確かに扱いが微妙だ…

関数の説明に data は dispose すると書くか
もしくは
`public static bool TryParseOrMigrate(string path, byte[] bytes, bool doMigrate, out Vrm10Data result)` のオーバーライドの方で using した方が良い感じはする

2022-01-26 02:35 UTC, notargs commented on Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/PrimitiveExtensions.cs
> +        public static NativeArray<Vector2>? GetTexCoords1(this glTFPrimitives primitives, GltfData data, int positionsLength)
`NativeArray.IsCreated` で存在確認できるので、nullableではなく、単に `NativeArray<Vector2>` としてdefalutを返す形のほうが処理負荷は軽そう。どっちがわかりやすいかは要検討

2022-01-26 03:35 UTC, ousttrue commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +                            _bin = CreateNativeArray(Chunks[1].Bytes);
最初コンストラクタにしてたのだが、
Dispose した後に再アクセスしても死なないように遅延させてました。
Dipose の呼ばれ方が変わったのでコンストラクタでよさそう。

2022-01-26 03:36 UTC, ousttrue commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfUtility.cs
> +    public static class GltfUtility
`byte[]` 引数版とかバリエーションはあとで必要に応じて。

2022-01-26 03:38 UTC, ousttrue commented on Assets/VRM10/Runtime/IO/Vrm10Data.cs
> +            using (data)
HLAPI である程度誤魔化せるのでよしとしようかなと。
1.0 はマイグレーションが有るのでシグネチャーに工夫が必要かもしれない(まだ作っていない)。

2022-01-26 03:39 UTC, ousttrue commented on Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/PrimitiveExtensions.cs
> +        public static NativeArray<Vector2>? GetTexCoords1(this glTFPrimitives primitives, GltfData data, int positionsLength)
なるほど。Require Dispose だと思ってた。

2022-01-26 05:24 UTC, ousttrue commented
手直し。と Test 修正。

## TODO

* 1.0 のマイグレーションが絡む場合に間違わずに書けるようにする
* `2019.4.30` テストランナーでまとめて実行したときに

`A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details.`

が不規則に発生する。(単体実行では発生しない)。

2022-01-26 06:06 UTC, Santarh approved these changes
LGTM

2022-01-26 06:06 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +        public NativeArray<byte> Bin { get; }
👍

2022-01-26 06:06 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +        List<IDisposable> m_disposables = new List<IDisposable>();
👍

2022-01-26 06:06 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +                    Bin = CreateNativeArray(Chunks[1].Bytes);
👍

2022-01-26 06:06 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
> +        public void Dispose()
👍

2022-01-26 06:07 UTC, merged