fix vrm mesh integration
vrm-c/UniVRM pull request #1577
Opened 2022-03-04 12:03 UTC by ousttrue

#1510

`MeshIntegratorWizard` を復活。
整理した。

* UserMenuPrefix + "/MeshIntegration" 廃止
* UserMenuPrefix + "/MeshIntegratorWizard" 修復
* exclude 実装
* assetのパス解決エラーなどの修正
* 実行結果の表示がmissingになるを修正

2022-03-04 12:09 UTC, Santarh requested changes
全体の UX として「除外を指定したい」はよさそう。

しかし `class MeshIntegrator` の設計としては、変えない方が綺麗だと思います。
`MeshIntegrator.Push(Renderer)` というメソッドがあるので、それを呼び出す側で
レンダラをフィルタする方が適切に思えます。

2022-03-04 12:50 UTC, Santarh requested changes
`class MeshIntegrator` の責務が曖昧になってきているので、どちらかに倒したいです。

2022-03-04 12:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs
> +        public MeshIntegrationResult Result;
Result は外から set されえないと思うので `{ get; private set; }` かなあ

2022-03-04 12:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs
>          public List<Vector3> Positions { get; private set; }
このクラスの `Positions` や `Normals` などが public になっているのは、このクラスの責務を「 `Push` されたレンダラをマージするだけ」にするためでした。

したがって、マージ結果を `Mesh` に実体化するところまでの責務をこのクラスでもつならば、これらの `List<T>` は public である必要がなさそうです。

2022-03-04 12:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs
> +        public void Intgrate(bool onlyBlendShapeRenderers)
もしくはこのメソッドと、Result と生成する責務は別のクラスに持っていくというのもアリかなとは思います。

2022-03-04 12:50 UTC, Santarh commented on Assets/UniGLTF/Runtime/MeshUtility/MeshIntegratorUtility.cs
> +                    if (exclude.IsExcluded(x))
👍

2022-03-07 05:23 UTC, ousttrue commented
private 化

2022-03-07 05:54 UTC, Santarh approved these changes

2022-03-07 06:06 UTC, merged