remove Unity.Mathmatics
vrm-c/UniVRM pull request #1669
Opened 2022-05-31 06:19 UTC by amamagi

2022-05-31 06:22 UTC, notargs requested changes
1点コメントしました 🙇

2022-05-31 06:22 UTC, notargs commented on Assets/VRM10/Runtime/FastSpringBone/System/UpdateFastSpringBoneJob.cs
> +        private static float Abs(float a) => a > 0 ? a : -a;
Mathf.Max、Mathf.Absでよさそう？

2022-05-31 06:38 UTC, amamagi commented on Assets/VRM10/Runtime/FastSpringBone/System/UpdateFastSpringBoneJob.cs
> +        private static float Abs(float a) => a > 0 ? a : -a;
Burstコンパイルできないかと思ってましたが、できましたのでMathfにします👍

2022-05-31 06:54 UTC, notargs approved these changes
LGTM 👍

2022-05-31 06:54 UTC, merged

2022-06-01 12:23 UTC, ousttrue commented
#1654