vrm の gltf Animation の読み書き仕様
vrm-c/UniVRM pull request #1719
Opened 2022-06-27 11:55 UTC by ousttrue

#1682

関連 #1522

* VRM は Animation を仕様に含めない
  => 未知の VRM をロードしたアプリケーションは、たとえ Animation が含まれていても用途が分からないであろう
  => エクスポートするの止めた #1522

* 自分でやっているので既知です #1682 
  => 自分用に glb のアニメーションを含められるように変更

以下のように UniVRM の動作を整理します。

|                | 新デフォルト    |コメント                                    | 既存の動作                                                 |
|----------------|---------------|------------------------------------|------------------------------------------------------------|
| editor export  | export しない | オプション指定でエクスポートできる | v0.96でエクスポートしなくなった                            |
| editor import  | import する   |                                    | インポートが動作してなかった(使わないので気にしてなかった) |
| runtime import | import しない | オプション指定でインポートできる   | Importされる                                               |

glb/glTF の動作変更はありません。

2022-06-27 12:01 UTC, ousttrue commented
![export_animation](https://user-images.githubusercontent.com/68057/175936520-6a6454e5-455f-44ca-ba03-5a512a271977.jpg)

2022-06-28 07:01 UTC, Santarh requested changes
基本的に LGTM ですが意図せず挙動変更してるところだけ１点

2022-06-28 07:10 UTC, ousttrue commented on Assets/VRM/Editor/Format/VRMEditorImporterContext.cs
> +                var meshPath = meshDir.Child(o.name.EscapeFilePath() + ".asset");
AnimationClip は '.anim'

2022-06-28 08:11 UTC, ousttrue commented on Assets/UniGLTF/Editor/Animation/EditorAnimationExporter.cs
>                  clips = AnimationExporter.GetAnimationClips(animation);
書き直してみた

2022-06-29 03:42 UTC, Santarh approved these changes

2022-06-29 03:42 UTC, Santarh commented on Assets/UniGLTF/Editor/Animation/EditorAnimationExporter.cs
> +                clips.AddRange(AnimationExporter.GetAnimationClips(animation));
`Animator` と `Animation` の両方がついていた場合
従来は `Animator` の Clip のみ列挙されていた。
これを `Animator` の Clip のあとに `Animation` の Clip が追加されるように変更される。

2022-06-29 03:53 UTC, ousttrue commented on Assets/UniGLTF/Editor/Animation/EditorAnimationExporter.cs
> +                clips.AddRange(AnimationExporter.GetAnimationClips(animation));
`Animator` と `Animation` の両方が Attach されているときに、 `Animation` に乗っている `AnimationClip` `も` 出力するための措置でした。いままでは、 `Animator` に `AnimationClip` が無い (Controller が無い)  場合でも、`Animation` から AnimationClip を取得することができなかった。
VRM のテストに使ったモデルが humanoid のために `Animator` を使い、AnimationClip のために `Animation` を使うという構成だったので、とりあえず。

2022-06-29 03:53 UTC, merged