runtime に BlendShapeProxy.m_merger を再初期化する
vrm-c/UniVRM pull request #1720
Opened 2022-06-28 05:30 UTC by ousttrue

fixed #1710

2022-06-28 07:13 UTC, Santarh requested changes
Breaking change が多そうなので意図しているのかどうかで気になりポイントです

2022-06-28 07:13 UTC, Santarh commented on Assets/VRM/Runtime/BlendShape/VRMBlendShapeProxy.cs
> +            if (merger != null)
挙動が変わってしまっている点が気になります。

`Start()` するより前の段階で `ImmediatelySetValue()` を呼び出すとその状態で初期化され SetValue が走ってしまう、ということになってしまっていると思います。

2022-06-28 07:13 UTC, Santarh commented on Assets/VRM/Runtime/BlendShape/VRMBlendShapeProxy.cs
> +                m_merger.RestoreMaterialInitialValues(BlendShapeAvatar.Clips);
これが Destroy されたあとにアクセスされることを考えると

正確にはここで `bool isDisposed` という変数に対して `true` を代入しておいて
`Merger` の `getter` では `if (isDisposed) return null;` というのを書いた方がよさそうです。

2022-06-28 07:23 UTC, ousttrue commented
Clear をやめて Reinitialize に変えます

2022-06-28 08:03 UTC, ousttrue commented on Assets/VRM/Runtime/BlendShape/VRMBlendShapeProxy.cs
> +
変化が少なくなるように、 `Clear` をやめて `Restart` に変更しました。

2022-06-29 03:56 UTC, Santarh approved these changes
よさそう。ただ `Restart` という名前だとなんだか気軽に呼んでいいような感じにも読める（別に気軽に呼んでもなんも起きないけど）

2022-06-29 03:56 UTC, Santarh commented on Assets/VRM/Runtime/BlendShape/VRMBlendShapeProxy.cs
> +
`Reinitialize()` などの方が命名としてはしっくりくるが、どうだろう。

2022-06-29 04:01 UTC, ousttrue commented on Assets/VRM/Runtime/BlendShape/VRMBlendShapeProxy.cs
> +
https://github.com/vrm-c/UniVRM/pull/1720/files#diff-21b8031f1a91629b829104f5142d6dd823982723e6e52be3f2bdc85dea128373R30-R39

と内容がほぼ同じ。ということは Start を呼ぶ関数にしよう 🤔

2022-06-29 04:09 UTC, Santarh approved these changes
LGTM

2022-06-29 04:10 UTC, merged