WebGLの動作確認
vrm-c/UniVRM pull request #1756
Opened 2022-07-26 05:39 UTC by ousttrue

VRM_Samples/SimpleViewer を WebGL ビルドする環境

* GltfUtility.LoadAsync の byte[] 引数
* VrmUtility.LoadAsync の byte[] 引数

あたりどうするか。

* RuntimeOnlyNoThreadAwaitCaller は動作確認できました。本物の Thread が無いのでそれなりの効果

![webgl](https://user-images.githubusercontent.com/68057/180931334-44e07332-ff7a-4225-81d4-e1a4894e0af3.jpg)

あと、 colorspace gamma が要求されるので色の再現性には目を瞑る。

2022-08-03 08:16 UTC, Santarh requested changes
全体 LGTM ですが、public な API が流石に驚き度が高すぎそうです

2022-08-03 08:16 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfUtility.cs
> +        public static async Task<RuntimeGltfInstance> LoadAsync(string path, IAwaitCaller awaitCaller = null, IMaterialDescriptorGenerator materialGenerator = null, byte[] bytes = null)
さすがにこれは関数分けましょう。FromPath と FromBytes は明確に分かれているべきです。
このクラスは simple な `ImporterContext` に対して、別軸に easy な API を提供するものだと思いますが
使用者から見て、驚き度が高すぎる引数と挙動になっていると考えます。

2022-08-03 08:16 UTC, Santarh commented on Assets/VRM/Runtime/IO/VrmUtility.cs
> +            byte[] bytes = null
これも同様。そもそもなぜ今までなかったんだろう？

2022-08-03 08:16 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniGLTF/IO/GltfUtility.cs
> +        public static async Task<RuntimeGltfInstance> LoadAsync(string path, IAwaitCaller awaitCaller = null, IMaterialDescriptorGenerator materialGenerator = null, byte[] bytes = null)
`Vrm10` の方は `LoadBytesAsync` と `LoadPathAsync` になっているので、それに合わせるのも良いと思います。

2022-08-03 08:20 UTC, ousttrue commented on Assets/VRM/Runtime/IO/VrmUtility.cs
> +            byte[] bytes = null
LoadBytesAsync 作ろう

2022-08-22 04:03 UTC, ousttrue commented
LoadBytesAsync に分離。
awaitCaller の警告前に、null 引数の throw。

2022-08-30 11:00 UTC, merged