Add IAwaitCaller to VRMImporterContext.LoadBlendShapeMaster
vrm-c/UniVRM pull request #1795
Opened 2022-09-14 02:14 UTC by matsutaka-pxv

この PR は、 `VRMImporterContext.LoadBlendShapeMaster` を async Task 化し、`IAwaitCaller` を与えます。これによって、 CPU スパイクの軽減を目指します。

このために、 `VRMImporterContext.LoadBlendShapeMaster` 内のループで `IAwaitCaller.NextFrameIfTimedOut()` を呼び出しています。

また、  `VRMImporterContext.LoadBlendShapeBind` も async 化しています。
これは、このメソッド内の連続した LINQ 処理に長い時間がかかる可能性があるためです。

2022-09-20 04:57 UTC, Santarh requested changes
全般 LGTM！
なんですが１点気になりポイントと、
あと特に明示されていないコーディング規約的なところで修正お願いします！

2022-09-20 04:57 UTC, Santarh commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                await LoadBlendShapeMaster(awaitCaller);
👍

2022-09-20 04:57 UTC, Santarh commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                    await awaitCaller.NextFrameIfTimedOut();
👍

2022-09-20 04:57 UTC, Santarh commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +        async Task<BlendShapeClip> LoadBlendShapeBind(IAwaitCaller awaitCaller, glTF_VRM_BlendShapeGroup group, Dictionary<Mesh, Transform> transformMeshTable)
他の箇所と合わせて `IAwaitCaller` は引数の最後にしてもらってよいですか？

2022-09-20 04:57 UTC, Santarh commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                                BaseValue    = material.GetColor(propertyName),
すみません、ここのコード整形は不要です

2022-09-20 04:57 UTC, Santarh commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                await awaitCaller.NextFrameIfTimedOut();
`materialValueBIndings` の変数定義時には `Select` 内の処理は走らないので、ここでの `await` は特に意味をなさないと思うのですが、いかがでしょう？

2022-09-20 04:57 UTC, Santarh commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                    await awaitCaller.NextFrameIfTimedOut();
👍

2022-09-20 14:26 UTC, matsutaka-pxv commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +        async Task<BlendShapeClip> LoadBlendShapeBind(IAwaitCaller awaitCaller, glTF_VRM_BlendShapeGroup group, Dictionary<Mesh, Transform> transformMeshTable)
[0029c1c](https://github.com/vrm-c/UniVRM/pull/1795/commits/0029c1cd5f68af3f2371bc2449e6bf74cb5c008e) にて修正しました。

2022-09-21 06:57 UTC, Santarh commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                await awaitCaller.NextFrameIfTimedOut();
なるほど！計測結果があるならば納得です。
本来、ラムダ式で多くの処理をするなら、ラムダ式ではなく関数定義しろってことですね……

2022-09-21 06:57 UTC, Santarh approved these changes
LGTM！ありがとうございました。

2022-09-21 07:23 UTC, merged