Offload reading glTF_VRM_Meta properties to other task
vrm-c/UniVRM pull request #1823
Opened 2022-09-21 11:11 UTC by matsutaka-pxv

`glTF_VRM_Meta` の持つプロパティには、長い時間がかかるものがあります。
このPRは `IAwaitCaller.Run()` を利用し、それを緩和するものです。

## 疑問点

カジュアルに `IAwaitCaller.Run()` を使用していますが、これが許されるものなのか、良く分かっていません。
手元の UnityEditor およびアプリケーションのターゲットでは問題無く動作していますが、WebGL等で困るケースがあり得るのか、事情を理解できていない部分があります。

2022-09-27 03:57 UTC, ousttrue commented
PR ありがとうございます。

IAwaitCaller.Run は、 `Task.Run` を使うのが目的です。(`RuntimeOnlyAwaitCaller` )

* Editor では Task.Run の結果が待てない (UnitTest とか Asset ローダーが終わらなくなる)
* WebGL ではそもそもスレッド無い( NextFrame だけ実装できる )

という状況から逃げるために、 `ImmediateCaller` の即時実行に逃げられるようになっています。

https://github.com/vrm-c/UniVRM/blob/master/Assets/VRMShaders/GLTF/IO/Runtime/AwaitCaller/ImmediateCaller.cs#L19

Unity での Task.Run (スレッド実行) の条件は、`Unity.Object にアクセスしない` であると心得ております。
さもないと、 Main thread じゃないアクセス違反になってしまいます。

`var meta = ScriptableObject.CreateInstance<VRMMetaObject>();`

なので、 スレッド上で ScriptableObject にアクセスすることになって例外になりそうな気がします。

2022-09-27 04:15 UTC, Santarh commented
はい、この問題があると認識しています。
それゆえに `IAwaitCaller` を導入しています。
たとえば `LoadAsync` 内部で `await` するために `Task` を好き勝手に作ると WebGL で問題になる可能性が高いです。
そこで `Task` は `IAwaitCaller` を経由してのみ作成することとしています。
これによって WebGL などの環境では `IAwaitCaller` の実装を切り替えることにより、問題を回避することができます。

> WebGL等で困るケースがあり得るのか

2022-09-27 04:38 UTC, Santarh requested changes
すみませんが、複数の理由でこの変更は避けたいです。

2022-09-27 04:38 UTC, Santarh commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                meta.Version = gltfMeta.version; // model version
`ScriptableObject` は `UnityEngine.Object` なので、メインスレッド外から関与するのは避けたいコードです。

- `meta` に触れるコンテキストが限られている
- `meta` のうち field にのみ作用している
というこの限定的な状況下ではうまくいくコードだとは思いますが、Editor といった想定外の状況も考えると避けるべきだと考えます。

2022-09-27 04:38 UTC, Santarh commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                meta.OtherLicenseUrl = gltfMeta.otherLicenseUrl;
このくらいの処理内容で `Run` すると、スレッドスタートコストの方が高くつきそうです（内部的にはもちろん Thread Pool でそのコストは最小限になっているとは思いますが）。

自分としてはこの処理内容がなんらか大きな負荷になっているとは考えにくいのですが、なっているのであれば
関数の最後に `await awaitCaller.NextFrame();` で十分じゃないでしょうか。

もしくは `TextureFactory.GetTextureAsync()` の負荷と一緒くたになっていないでしょうか？

2022-09-28 03:15 UTC, matsutaka-pxv commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                meta.OtherLicenseUrl = gltfMeta.otherLicenseUrl;
`UniGLTF.Utils.CachedEnum.TryParseOrDefault<T>` の処理にはとても長い時間がかかります。

例えば、以下のように `VRM.glTF_VRM_Meta.allowedUser` を計測すると、手元では 1 ～ 2 ms 程度の結果となります。

```C#
{
    /* + */ var t0 = Time.realtimeSinceStartup;

    meta.AllowedUser = gltfMeta.allowedUser;

    /* + */ var t1 = Time.realtimeSinceStartup;
    /* + */ Debug.Log($"dt={(t1-t0)*1000.0} ms");   // 1 .. 2 ms
}
```

以下の `VRM.glTF_VRM_Meta.licenseType` も同様です

```C#
{
    /* + */ var t0 = Time.realtimeSinceStartup;

    meta.AllowedUser = gltfMeta.licenseType;

    /* + */ var t1 = Time.realtimeSinceStartup;
    /* + */ Debug.Log($"dt={(t1-t0)*1000.0} ms");   // 1 .. 2 ms
}
```

2022-09-28 03:32 UTC, matsutaka-pxv commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                meta.Version = gltfMeta.version; // model version
「たまたま動いている」状態であるのはご指摘の通りなので、リードとライトを正確に分ける形に変更します。

2022-09-28 03:45 UTC, matsutaka-pxv commented
レビューありがとうございます。以下のような変更案を考えました。

### 案(1)

`IAwaitCaller.Run()` は使用したまま、一次変数を経由して、アクセス違反の可能性を防ぐ

```C#
string version = default;
AllowedUser allowedUser = default;
LicenseType licenseType = default;
...

await awaitCaller.Run(() =>
{
    version = gltfMeta.version;
    allowedUser = gltfMeta.allowedUser;
    licenseType = gltfMeta.licenseType;
    ...
});

meta.Version = version;
meta.AllowedUser = allowedUser;
meta.LicenseType = licenseType;
...
```

長所
- `glTF_VRM_Meta` の実装が変更されて処理速度が変わった場合、自動的にオフローディングできる。

短所
- 同じ名前が繰り返され、実装が嵩張っている
- いつも `IAwaitCaller.Run()` が別コンテキストで実行される可能性があることを意識する必要がある



### 案(2)

元の形式に戻し、時間のかかる (or かかりそうな) 処理の後ろに `IAwaitCaller.NextFrameIfTimedOut()` を適宜追加する。

```C#
meta.AllowedUser = gltfMeta.allowedUser;
awaitCaller.NextFrameIfTimedOut();

...

meta.LicenseType = gltfMeta.licenseType;
awaitCaller.NextFrameIfTimedOut();
```

長所
- 従来通りの挙動を保てる
- 差分が少ない

短所
- `glTF_VRM_Meta` の実装、処理時間を監視し、処理が重くなったときは適宜 `IAwaitCaller.NextFrameIfTimedOut()` を追加する必要がある

2022-09-28 03:45 UTC, ousttrue commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                meta.OtherLicenseUrl = gltfMeta.otherLicenseUrl;
CachedEnum は Enum.GetValues と Enum.Parse で都度 GC が発生するのを、名前の通りキャッシュするものです。

https://github.com/vrm-c/UniVRM/blob/master/Assets/UniGLTF/Runtime/Utils/CachedEnum/CachedEnumType.cs

初回コストが発生します。
初回コストが許容できない場合、VRM をロードするより前、アプリ開始くらいのタイミングで CachedEnum を適当に呼び出すことで事前にキャッシュを構築するのが良いと思います。
このキャッシュの構築はスレッド上で実行しても問題ありません。

```cs
// たぶん、こんな感じ
static void InitEnumCache()
{
// 使いそうな型を手書き
    UniGLTF.Utils.CachedEnum.TryParseOrDefault<A>();
    UniGLTF.Utils.CachedEnum.TryParseOrDefault<B>();
    UniGLTF.Utils.CachedEnum.TryParseOrDefault<C>();
    UniGLTF.Utils.CachedEnum.TryParseOrDefault<D>();
    UniGLTF.Utils.CachedEnum.TryParseOrDefault<E>();
}

// アプリ開始時などに早期にキャッシュ構築。static 変数なのでメモリにずっと残る
Task.Run(InitEnumCache); // 投げっぱなし
```

2022-10-05 07:48 UTC, matsutaka-pxv commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                meta.OtherLicenseUrl = gltfMeta.otherLicenseUrl;
ありがとうございます。

可能であれば、このPRは閉じて、お知らせ頂いた方法を以下のように UniVRM 内で実装するPRを新規に送りたいと思うのですが、どうでしょうか？

```C#
namespace VRM {
    // もっと良い場所があるかもしれない
    public class VRMImporterContext : ImporterContext {
        ...
        private static bool prewarmed = false;

        // この関数はアプリ側から明示的に呼び出す。
        // Prewarm ではなく Initialize 等の名前が適切かもしれない
        pubilc static void Prewarm() {
            if (prewarmed) {
                return;
            }
            prewarmed = true;
            UniGLTF.*.Prewarm();  // InitEnumCache() 相当の処理などを呼ぶ
            ...                   // 他にも増えるかもしれない
        }
        ...
    }
}
```

アプリ側ではなく、 UniVRM 内で初期化 (あるいはキャッシュのプリウォーム) を行いたい理由は以下になります

- アプリ側で UniGLTF の実装を知らなくても良い。また、将来の UniGLTF の変更に追従しなくても良い
- UniVRM 内で他にも初期化やプリウォームを行える処理があった場合、同じ仕組みを利用できる

不要であれば、単純にこのPRを閉じて、完了としたいと考えています。

2022-10-05 08:04 UTC, ousttrue commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                meta.OtherLicenseUrl = gltfMeta.otherLicenseUrl;
了解です。`Initialize` 関数でお願いいたします。
内容的に、計測しづらいものになりそうです。
特に Editor 実行時に static 変数のクリアが、予測しづらい感じになりそう。
おそらく、初回と Compile  後の初回になったりしそう。

2022-10-05 08:39 UTC, matsutaka-pxv commented on Assets/VRM/Runtime/IO/VRMImporterContext.cs
> +                meta.OtherLicenseUrl = gltfMeta.otherLicenseUrl;
ありがとうございます。本件はクローズします。

> 内容的に、計測しづらいものになりそうです。
> 特に Editor 実行時に static 変数のクリアが、予測しづらい感じになりそう。
> おそらく、初回と Compile 後の初回になったりしそう。

ご指摘の通り、非 IL2CPP ビルドを行ったアプリを用いて、なおかつ自動計測を行わないと計測しにくいものです。

現状の VRM 対応アプリでの、エンドユーザさんの体験に近い環境だとは思いますが、
極端である、あるいは現実的に維持しにくい（問題があっても無くても気づきにくい）面もあると想像しています。

できるだけ維持しやすいものになると良いと考えています。

2022-10-05 08:40 UTC, matsutaka-pxv commented
https://github.com/vrm-c/UniVRM/pull/1823#discussion_r987641275 に従い、本件はクローズします。

2022-10-05 08:40 UTC, closed without merging