[1.0][0.x] SpringBone の手動更新
vrm-c/UniVRM pull request #1886
Opened 2022-10-24 10:13 UTC by ousttrue

fixed #1869

2022-10-25 07:09 UTC, 0b5vr commented
deltaTimeを指定することはできませんか？

`Time.deltaTime` を使うと、その瞬間のdeltaTimeが60回連続で使われることになってしまい、変な運試しが発生してしまいそうです。

VRM1.0のfastSpringBoneの方は、もともとdeltaTimeを渡すインタフェースが無いのですね。

2022-10-25 07:10 UTC, ousttrue commented
PR おなしゃす

2022-10-25 10:39 UTC, ousttrue commented on Assets/VRM/Runtime/SpringBone/VRMSpringBone.cs
> +        public void ManualUpdate(float deltaTime)
deltaTime 追加

2022-10-25 10:43 UTC, ousttrue commented
fastSpringBone の方は job になっているのであまり自由ではないようです。
一か所で連続呼び出しするより、実際にフーレムを進めた方がいいんじゃないだろうか。

```cs
for(int i=0; i<10; ++i)
{
  await nextFrame(); // 的な
}
```

2022-10-25 11:03 UTC, Santarh reviewed
VRM10 において SpringBone は Expression や Constraint の解決よりも後ろで実行されなければなりません。
デフォルトでは自動的に実行されているので、ユーザはそれを意識する必要はほとんどありません。

しかし手動アップデートを API 提供するなら話が変わってきます。
ユーザはこの順序に関する知識を得て呼び出さなければなりません。

しかし、この知識は本当に必要でしょうか？
どうせ順序正しく呼び出さなければ `ならない` のであれば、隠ぺいしてしまった方が良いのではないかなと思います。
具体的には SpringBone の更新は UnityEvent 起因では呼び出さず、手動のみにしてしまう。
そして Vrm10Runtime で SpringBone の更新を呼び出す。
この方がユーザは考えることや知ることが少ないし、我々にとっても保守しやすいと思います。

2022-10-25 13:00 UTC, ousttrue commented
FastSpringBoneService (シングルトン) は、複数モデルを同時に扱うときのパフォーマンス最適化です。
デフォルトでは Vrm10Runtime の支配下に一人用の FastSpringBone  があって、
複数人最適化は import オプションが良いかも。
どちらの場合も job system の恩恵はあります。`v0.107` 以降の課題

2022-10-26 02:40 UTC, notargs requested changes
数点、可読性の観点からレビューしました。
大枠の変更は問題なさそうです 👍

2022-10-26 02:40 UTC, notargs commented on Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneScheduler.cs
> +        /// 4. PushTransformJob
これはコードから読み取れるので、実質的にメンテナンスせねばならないコードが二重になっていそう
変更漏れによってコードとコメントが乖離するのがめんどいので、単に要約するのでなく、「これを読み取れるだけの知識を読み手に与える」方針でコメントを書くとよりわかりやすく、メンテナンス性も高そう

2022-10-26 02:40 UTC, notargs commented on Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneScheduler.cs
> +            }.Schedule(_bufferCombiner.Springs.Length, 1, handle1);
「元のコードでは直列に繋いでるように見えない」という意図だと思いますが
この新しいコードでもパッと見で直列に繋いでいるようには見えず、
また、例えばここで誤って `handle0` を渡してしまうなどのエンバグリスクが生まれているため、この変更は避けたいです

2022-10-26 02:40 UTC, notargs commented on Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneService.cs
> +        public enum UpdateTypes
🍰 Inner classはあまりメリットが無いため、特別な理由がなければasmdefスコープで定義したい

2022-10-26 02:40 UTC, notargs commented on Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneService.cs
> +            _fastSpringBoneScheduler.Schedule(deltaTime).Complete();
シンプル 👍

2022-10-26 02:40 UTC, notargs commented on Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneScheduler.cs
> +                DeltaTime = deltaTime,
note: Jobはワーカースレッドで走るため、Time.deltaTimeにアクセスすることはできない
よって、この時点でTime.deltaTimeを渡していたが、そのおかげで外出しもしやすかった

2022-10-26 04:24 UTC, ousttrue commented on Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneScheduler.cs
> +            }.Schedule(_bufferCombiner.Springs.Length, 1, handle1);
そういうと思った。
元に戻そう。
handle 流用はすごいよみづらい。

2022-10-26 04:25 UTC, ousttrue commented on Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneService.cs
> +        public enum UpdateTypes
他のところでそうしているので、スタイルを合わせている

2022-10-26 04:36 UTC, ousttrue commented on Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneScheduler.cs
> +            }.Schedule(_bufferCombiner.Springs.Length, 1, handle1);
```cs
            var handle = _bufferCombiner.ReconstructIfDirty(default);
            if (!_bufferCombiner.HasBuffer)
            {
                return handle;
            }

            return new PushTransformJob
            {
                Transforms = _bufferCombiner.Transforms
            }.Schedule(_bufferCombiner.TransformAccessArray, new UpdateFastSpringBoneJob
            {
                Colliders = _bufferCombiner.Colliders,
                Joints = _bufferCombiner.Joints,
                Logics = _bufferCombiner.Logics,
                Springs = _bufferCombiner.Springs,
                Transforms = _bufferCombiner.Transforms,
                DeltaTime = deltaTime,
            }.Schedule(_bufferCombiner.Springs.Length, 1, new PullTransformJob
            {
                Transforms = _bufferCombiner.Transforms
            }.Schedule(_bufferCombiner.TransformAccessArray, handle)));
        }
```
やや明瞭だが、読みやすくはない。

2022-10-26 08:13 UTC, notargs approved these changes
LGTM 👍

2022-10-26 08:16 UTC, merged