Add limit break sliders to spring bone joint properties
vrm-c/UniVRM pull request #1952
Opened 2022-12-08 11:43 UTC by 0b5vr

### Description

SpringBoneの各パラメータ（stiffness, gravityPower, jointRadius）に対して、スライダーの範囲は従来のまま、数値入力の際にスライダーの範囲を超えて入力できるように変更しました。
VRM0・VRM1の双方に変更を適用しました。

2022-12-09 06:54 UTC, Santarh requested changes
ありがとうございます。実際に clone して動作確認したところよさそうです。
いくつか細かいところで修正お願いします。

2022-12-09 06:54 UTC, Santarh commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +    class VRM10SpringBoneJointEditor : Editor
VRM 0.x 用のクラスも作っていただいたんですね、ありがとうございます……
なんですが、クラス名に `10` についているので消していただけると…

2022-12-09 06:54 UTC, Santarh commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +            m_updateTypeProp = serializedObject.FindProperty("m_updateType");
string リテラル指定の代わりに C# の `nameof` 式を使うと、IDE が追跡できるので保守性が上がります。
具体的には以下のように書きます。

```csharp
m_commentProp = serializedObject.FindProperty(nameof(VRMSpringBone.m_comment));
...
```

2022-12-09 06:54 UTC, Santarh commented on Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs
> +            m_jointRadiusProp = serializedObject.FindProperty("m_jointRadius");
同じく `nameof` 式を使える場所

2022-12-09 06:54 UTC, Santarh commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +                    property.floatValue = sliderValue;
スライダーに変更があったときにだけ、反映される。
つまり限界突破中にうっかり Slider Max Value に戻ることは無い、はず…

2022-12-09 06:54 UTC, Santarh commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +        private static void LimitBreakSlider(SerializedProperty property, float sliderLeft, float sliderRight, float numberLeft, float numberRight)
限界突破スライダー自体はよさそうです

2022-12-09 06:54 UTC, Santarh commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +    class VRM10SpringBoneJointEditor : Editor
複数の Component を選択したときに一気に編集できるかどうか、という属性があります。
今の状態だと無効化されています。
`[CanEditMultipleObjects]` を付与してもらえるでしょうか。
現状のコードはすべて Unity の Field を使っていて、自作の Field は無いので、それだけで動くようになります。

2022-12-09 06:54 UTC, Santarh commented on Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs
> +    class VRM10SpringBoneJointEditor : Editor
同じく `[CanEditMultipleObjects]`

2022-12-09 06:57 UTC, 0b5vr commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +    class VRM10SpringBoneJointEditor : Editor
ごめんなさい、お名前変え忘れておりました。

`[CanEditMultipleObjects]` 、了解です。

2022-12-09 07:00 UTC, 0b5vr commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +    class VRM10SpringBoneJointEditor : Editor
対応しました @ https://github.com/vrm-c/UniVRM/pull/1952/commits/907f8ec33faf548d5e1b1e68d2628d0ac841caeb, https://github.com/vrm-c/UniVRM/pull/1952/commits/a56bdbb3fe314d3da172237407d10ce817207de4

2022-12-09 07:00 UTC, 0b5vr commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +            m_updateTypeProp = serializedObject.FindProperty("m_updateType");
`nameof` 了解です。

2022-12-09 07:04 UTC, 0b5vr commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +            m_updateTypeProp = serializedObject.FindProperty("m_updateType");
対応しました @ https://github.com/vrm-c/UniVRM/pull/1952/commits/9c194d55e72a3a71a4fedb4cbb6a9c91130a259d

`m_gizmoColor` はprivate memberのため、リフレクションでしか指定ができなさそうでした。
このままリフレクションにするか、private指定をpublicにするかが択だと思います。いかがいたしましょう？

2022-12-09 07:04 UTC, 0b5vr commented on Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs
> +            m_jointRadiusProp = serializedObject.FindProperty("m_jointRadius");
対応しました @ https://github.com/vrm-c/UniVRM/pull/1952/commits/9c194d55e72a3a71a4fedb4cbb6a9c91130a259d

2022-12-09 07:10 UTC, Santarh commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +            m_updateTypeProp = serializedObject.FindProperty("m_updateType");
Gizmo に関しては諦めてこのまま string リテラルでいいかなと思います。

VRM 0.x 用コンポーネントに関しては、public にすることで今さらあまり定義を変更したくないという気持ちです。
ファイルに出力するにあたって重要なプロパティでもないですし

2022-12-12 05:41 UTC, Santarh approved these changes
LGTM

2022-12-12 05:41 UTC, Santarh commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +            m_gizmoColorProp = serializedObject.FindProperty("m_gizmoColor");
gizmo は仕方ない。あとはヨシ

2022-12-12 05:42 UTC, merged