Fix exporter texture leak
vrm-c/UniVRM pull request #1978
Opened 2023-01-25 09:48 UTC by ousttrue

* TextureExporter に `IDisposableResourceList` を実装
* TextureExporter.Dispose を呼び出すように修正

glb の pbr 関連テクスチャーの変換で動作することを確認。

2023-01-25 09:49 UTC, ousttrue commented on Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/TextureExporter.cs
> +            return (texture2D, disposable);
dispose する必要を運ぶ方法

2023-01-26 06:26 UTC, ousttrue commented on Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/TextureExportParam.cs
> +        public Func<(Texture2D Texture, bool IsDisposable)> Creator { get; set; }
tuple に IsDisposable と名前を付けた

2023-01-26 06:29 UTC, ousttrue commented
IsDisposalbe = true を不必要につけると余計なものが解放されて危険。
テクスチャーが `TextureConverter.CopyTexture` に由来するもので、大丈夫であろうというところに true を付けた。

2023-01-26 07:15 UTC, Santarh requested changes
よさそう。
`PushDisposable` は `public` じゃなくてもいいかなと思った

2023-01-26 07:15 UTC, Santarh commented on Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/ITextureExporter.cs
> +    public interface ITextureExporter: IDisposable
`ITextureExporter` は出力完了後に破棄すべきリソースを保持する可能性がある

2023-01-26 07:15 UTC, Santarh commented on Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/TextureExporter.cs
> +        private readonly List<UnityEngine.Texture2D> _disposables = new List<UnityEngine.Texture2D>();
`TextureExporter` は出力完了後に破棄すべき `Texture2D` を生成する

2023-01-26 07:15 UTC, Santarh commented on Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/TextureExporter.cs
> +        public void PushDisposable(UnityEngine.Texture2D disposable)
`TextureExporter` は外から入力された `TextureExportParam` を基に `Texture2D` を生成する責務がある。
したがってその内部処理上 `new` される `Texture2D` のことだけを考えれば良いので
 `public` である必要性はなさそう

2023-01-26 07:15 UTC, Santarh commented on Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/TextureExporter.cs
> +                disposable = true;
👍

2023-02-09 10:04 UTC, Santarh approved these changes

2023-02-09 10:04 UTC, merged