[sample] VRM10Retarget の実装
vrm-c/UniVRM pull request #1992
Opened 2023-02-21 08:30 UTC by ousttrue

#1990 を使ってみた。
innterface の修正。

2023-02-21 08:31 UTC, ousttrue commented on Assets/VRM10/Runtime/ControlRig/ITPoseProvider.cs
>      public interface ITPoseProvider
TPose インタフェースを整理。この３つで全部得られる

2023-02-21 08:33 UTC, ousttrue commented on Assets/VRM10_Samples/VRM10Viewer/VRM10Loaded.cs
> -        public void UpdateControlRigExplicit(Animator src)
ControlRig にポーズをセットする概念が INormalizedPoseProvider と INormalizedPoseApplicable になった

2023-02-21 08:33 UTC, ousttrue commented on Assets/VRM10_Samples/VRM10Viewer/VRM10Motion.cs
> +        #region experimental vrm-animation deserializer
これは次の準備。まだ使ってない

2023-02-21 08:37 UTC, ousttrue commented on Assets/VRM10_Samples/VRM10Viewer/VRM10Retarget.cs
> +        }
TPose を使って hips の移動値スケーリングをする例

2023-02-27 05:32 UTC, Santarh requested changes
幾つかコメントしました

2023-02-27 05:32 UTC, Santarh commented on Assets/VRM10_Samples/VRM10Viewer/VRM10Retarget.cs
>      public static class VRM10Retarget
普通の名前空間で公開すると紛らわしいので
この Sample 以下のクラスの名前空間は `UniVRM10.VRM10Viewer` になっているのでそれにしませんか？

2023-02-27 05:32 UTC, Santarh commented on Assets/VRM10/Runtime/ControlRig/ITPoseProvider.cs
> +        IEnumerable<(HumanBodyBones Head, HumanBodyBones Parent)> EnumerateBoneParentPairs();
これは実在するボーン間の組み合わせが返るものですか？
たとえば

- chest ある
- upperChest ない
- neck ある

という場合には `(chest, neck)` が含まれますか？

2023-02-27 05:32 UTC, Santarh commented on Assets/VRM10/Runtime/ControlRig/ITPoseProvider.cs
> +        IEnumerable<(HumanBodyBones Head, HumanBodyBones Parent)> EnumerateBoneParentPairs();
あとこの組み合わせにおいて `Head` は適切ではないネーミングだと思われます。
そもそも Head ボーンがあるのもそうですが、一般にボーンにおける Head は、ある単一のボーンに Head-Tail の概念がある時に使われる言葉だと思われます。

この場合は `(HumanBodyBones Bone, HumanBodyBones ParentBone)` などで良いと思います

2023-02-27 05:32 UTC, Santarh commented on Assets/VRM10/Runtime/ControlRig/ITPoseProvider.cs
> +        /// * bone 無いときは throw するべし
このコメントには実装者に対するものではなく、利用者に対するものを記述したほうが良いと思います。
たとえば
> 指定された bone が存在しないときは例外がスローされます。

など。

2023-02-27 05:32 UTC, Santarh commented on Assets/VRM10/Runtime/ControlRig/ITPoseProvider.cs
> +        /// * bone 無いときは throw するべし
それはそれとして、あまり例外が返ってくることを期待するような関数でもない気がします。
返り値を `Quaternion?` にするのはどうでしょうか？

2023-02-27 05:32 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniHumanoid/Format/Bvh.cs
> -    public class BvhException : Exception
BVH に関する変更はどうやらリファクタリングのようなのでさっと見ます

2023-02-27 05:32 UTC, Santarh commented on Assets/VRM10/Runtime/ControlRig/AnimatorPoseProvider.cs
> +        #region INormalizedPoseProvider
個人的には region は、やむを得ず 1000 行以上あるようなファイルで仕方なく使うものという認識があります。
逆にこの程度の行数で region を使うのは結構見づらいという感覚があります。

region の代わりにインタフェースの明示的実装の手段をとれば、なんのインタフェースのための実装か明示できて良いと思います。

2023-02-27 06:25 UTC, ousttrue commented on Assets/VRM10/Runtime/ControlRig/ITPoseProvider.cs
> +        IEnumerable<(HumanBodyBones Head, HumanBodyBones Parent)> EnumerateBoneParentPairs();
以下の２つについて制御することを意図しています。

- 必須でないボーン(UpperChest など)の有無
- HumanoidBone でないボーンが間に入っている場合

用例
```cs
            foreach (var (head, parent) in sink.TPose.EnumerateBoneParentPairs())
            {
                // 例えばソース側に neck1(HumanBodyBones.Neck), neck2, head(HumanBodyBones.Head) がある場合に
                // head.localRotation では具合が悪い。
                var q = source.Pose.GetNormalizedLocalRotation(head, parent);
                sink.Pose.SetNormalizedLocalRotation(head, q);
            }
```

2023-02-27 06:57 UTC, Santarh approved these changes

2023-02-27 08:39 UTC, merged