[experimental][vrm-animation] vrm animation の試験実装
vrm-c/UniVRM pull request #2000
Opened 2023-03-03 04:20 UTC by ousttrue

2023-03-03 04:24 UTC, ousttrue commented on Assets/UniGLTF/Runtime/UniHumanoid/SkeletonMeshUtility.cs
> +        readonly struct TSRBox
このあたり BoxMan のメッシュ generator の更新。

2023-03-03 04:24 UTC, ousttrue commented on Assets/VRM10/Editor/Vrm10SerializerGenerator.cs
> +                ),
`VRMC_vrm_animation` のコード生成

2023-03-03 04:25 UTC, ousttrue commented on Assets/VRM10_Samples/VRM10Viewer/VRM10Motion.cs
> +    }
BvhMotion: IMotion と VrmAnimation: IMotion の２種類

2023-03-06 04:39 UTC, Santarh requested changes
関数の切り出しだけお願いします

2023-03-06 04:39 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs
> +                uniqueName.ForceUniqueName(t);
ボーンをユニーク名にしなければ Humanid Avatar が上手く構築できないというのは知っていますし
それの解決を行うことはやるべきだと思うんですが、
 `ToHumanDescription` という `HumanDescription` を生成する関数で副作用的に名前が変えられてしまうのは、
あとからコードを見返したときに、気づけないバグ的挙動に見えてしまいます。
特に、VRM 側にも影響する挙動だと思うので、注意したいです。

処理を `SetTransformNameUnique()` みたいな関数に切り出せないでしょうか？

2023-03-06 04:39 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs
> +                uniqueName.ForceUniqueName(t);
あと VRM 0.x/1.0 的に、ボーンの名前を参照するようなプロパティはおそらくなかったはずなので、そちらの問題はない…はず？

2023-03-06 08:53 UTC, ousttrue commented on Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs
> +                uniqueName.ForceUniqueName(t);
UniqueName 機能を GlbLowLevelParser.FixNodeName に移動させました

2023-03-06 09:01 UTC, Santarh commented
Jenkins

2023-03-06 09:40 UTC, Santarh approved these changes
yosi

2023-03-06 09:40 UTC, Santarh commented on Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs
> +            }
こればっかりは Unity Humanoid Mecanim Avatar の制約なのでしかたない

2023-03-06 09:44 UTC, merged