[vrm1.0] impl refactor mesh integration
vrm-c/UniVRM pull request #2180
Opened 2023-10-27 07:21 UTC by ousttrue

#2169 の部品

List<Renderer> を統合するシンプルなインタフェースに改変。
exclude や統合対象を調整する責務は呼び出し側に移動した。

2023-10-27 07:22 UTC, ousttrue commented on Assets/UniGLTF/Editor/MeshUtility/TabMeshIntegrator.cs
> -                var mesh = result.IntegratedRenderer.sharedMesh;
result には Renderer 乗せない(sharedMesh, sharedMaterials, bones を保持する)

2023-10-27 07:23 UTC, ousttrue commented on Assets/UniGLTF/Runtime/MeshUtility/BoneNormalizer.cs
> +        public static void WriteBackResult(GameObject go, GameObject normalized, Dictionary<Transform, Transform> boneMap)
copy せずにヒエラルキーを直接改変するために作った。
TODO: undo に対応する。

2023-10-27 07:24 UTC, ousttrue commented on Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs
> +        public static MeshIntegrationResult Integrate(MeshIntegrationGroup group, bool useBlendShape)
MeshEnumerateOption を見て‘Renderer を収集する責務を外に移動。

2023-10-27 07:25 UTC, ousttrue commented on Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs
> +        public static Avatar RecreateAvatar(Animator src)
親子関係は変わっていないが transform が変わったヒエラルキーに対して
avatar を再作成する関数。

2023-10-31 04:41 UTC, Santarh requested changes
using に関してだけ

2023-10-31 04:41 UTC, Santarh commented on Assets/VRM10/Runtime/MeshUtility/Vrm10MeshUtility.cs
> +using System.Net.WebSockets;
おそらく Reference ミス？コンパイル通らなくなる場合ありそうなので消してもらえると

2023-10-31 04:41 UTC, Santarh commented on Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs
> +using System.Runtime.CompilerServices;
こちらも不要な using？
どうでもいいものならいいんですが CompilerServices は特定環境でマズそう

2023-10-31 07:45 UTC, merged