avatar 代入時に姿勢が変わる対策
vrm-c/UniVRM pull request #2208
Opened 2024-01-04 07:19 UTC by ousttrue

fixed #2201

```cs
animator.avatar = newAvatar
```

としたときに元の値を維持する？挙動があります。
そのため 旧avatar と newAvatar で元になる姿勢が異なる(例えば正規化)場合に姿勢が壊れます。
対策として、 Destory(Animator) して作り直します。

`v0.116` より前はヒエラルキーをコピーしていたため代入時の元の値を維持する挙動をたまたま回避できていたようです。
`v0.116` はコピーせずに同一のヒエラルキーで実行します。

2024-01-05 04:48 UTC, Santarh commented
むしろここが気になったんですが、現状の実装では Export 対象の GameObject に破壊的変更を加えるようにしたということですか？

> v0.116 はコピーせずに同一のヒエラルキーで実行します。

ユーザから見ると予想しづらい（困った）挙動になっていると感じます。
すくなくとも Editor での Export の場合、素直にコピーした方が実装も挙動もシンプルになりそうですがどうなんでしょう？

2024-01-05 05:12 UTC, Santarh commented
さすがにそれはなくて、元の GameObject 自体は不変で、コピーしたものを操作して出力しているか。

https://github.com/vrm-c/UniVRM/blob/197efa5fb2524e2f4d8a8c020c1a27cca5fc3fab/Assets/VRM/Editor/Format/VRMEditorExporter.cs#L154

2024-01-05 05:21 UTC, Santarh commented
なるほど。ここでいう `ヒエラルキーをコピーして` いたのは、以前の `BoneNormalizer` の中のこの実装のことですか。
理解しました。

https://github.com/vrm-c/UniVRM/pull/2179/files#diff-1fdf808babd75944390d7cde67671e618c54d4e4c49358e9d3ec81f2b24508b4L514

2024-01-05 06:12 UTC, ousttrue commented
> ２回も GameObject を Duplicate 

うろ覚えですが、
prefab で動くようにしたあたりで、2つめのコピーが増えたのかもしれない。
editor なので安全に倒してあるのだと思います。

2024-01-09 04:02 UTC, Santarh requested changes
LGTM、コメント追従だけ

2024-01-09 04:02 UTC, Santarh commented on Assets/VRM/Runtime/SkinnedMeshUtility/VRMBoneNormalizer.cs
>          /// <returns>正規化済みのモデル</returns>
コメント更新が追い付いてないですね。
ついでに破壊的操作であることも書いておくといいのかも

2024-01-09 04:43 UTC, Santarh approved these changes

2024-01-09 04:46 UTC, merged

2024-01-18 04:59 UTC, FujiSunflower commented
報告が２つあります。
1. Destory(Animator)とDestroyImmediate(Animator)の分岐の箇所がありましたが、Destory(Animator)の場合ランタイムで次フレームに移らないと削除されないので、DestroyImmediate(Animator)の方が良さそうでした。
2. 表情の正規化が上手く行っていないような気がしました。これに関しては自分がややこしい手順をしてる可能性もあります。