add BlittableExternalData.Paused
vrm-c/UniVRM pull request #2363
Opened 2024-07-16 09:23 UTC by ousttrue

fixed #2347

サンプルのシーン更新入っています。

2024-07-16 09:25 UTC, ousttrue commented on Assets/VRM10/Runtime/FastSpringBone/System/UpdateFastSpringBoneJob.cs
>                  Logics[logicIndex] = logic;
pause 時も処理は継続する。
これにより再開時の暴れない。
一時停止とロード時の暴れ防止の共用にできる。

2024-07-16 09:43 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs
> +        public bool SpringBonePaused
あとこのプロパティが生えるとなると、さすがに `Vrm10Runtime` に `Vrm10RuntimeSpringBone` を生やしてリファクタリングしたいですね…

2024-07-16 10:20 UTC, ousttrue commented on Assets/VRM10/Runtime/FastSpringBone/Blittables/BlittableExternalData.cs
> +        public bool IsSpringBoneEnabled;
pause あらため IsSpringBoneEnabled;

2024-07-16 10:25 UTC, Santarh requested changes
あと１点だけ！

2024-07-16 10:25 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs
> +        [Obsolete("use Vrm10Runtime.SpringBone.ExternalForce")]
👍

2024-07-16 10:25 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs
> +        public Vrm10RuntimeSpringBone SpringBone { get; }
👍

2024-07-16 10:25 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
> +    public class Vrm10RuntimeSpringBone : IDisposable
👍

2024-07-16 10:25 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
> +        public Vrm10RuntimeSpringBone(Vrm10Instance instance)
そんなに意味はない気はしてるんですけど、ほかの Runtime クラスのコンストラクタが全部 `internal` になっているので揃えておいてもらえますか？

2024-07-16 10:25 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
> +        public bool IsSpringBoneEnabled
`Vrm10RuntimeSpringBone` 以下にあるなら `IsEnabled` でもいい気はしてきたけど
対象が明確な方がまあいいか

2024-07-16 10:25 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
> +    public class Vrm10RuntimeSpringBone : IDisposable
いずれ「デフォルト状態に戻す」関数とか生やしたいですね

2024-07-16 10:25 UTC, Santarh commented on Assets/VRM10/Runtime/FastSpringBone/Blittables/BlittableExternalData.cs
> +        public bool IsSpringBoneEnabled;
👍

2024-07-16 10:28 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
> +        public Vrm10RuntimeSpringBone(Vrm10Instance instance)
（public になるべき要望が来たらそのとき public にするほうが API Breaking Change にならない）

2024-07-17 05:45 UTC, ousttrue commented on Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBufferBuilder.cs
> +    public class FastSpringBoneBufferBuilder
主に dots 向けに list の list を flatten するユーティリティ。独立

2024-07-17 05:45 UTC, ousttrue commented on Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
> +                    m_loaded.Runtime.SpringBone.RestoreInitialTransform();
reset spring ボタン

2024-07-17 05:46 UTC, ousttrue commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
> +        public void RestoreInitialTransform()
> デフォルト状態に戻す 関数

2024-07-18 01:48 UTC, Santarh requested changes
機能面は LGTM です。

`FastSpringBoneBufferBuilder` の分割は不要かつコードが不安定になっていると思うのでその点だけ。

2024-07-18 01:48 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
> +            set { m_fastSpringBoneBuffer.ExternalForce = value; }
ちなみに setter も 1 式で済むなら `set => foo = value;` の形式で書けますよ

2024-07-18 01:48 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
> +        internal Vrm10RuntimeSpringBone(Vrm10Instance instance)
👍

2024-07-18 01:48 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
> +                ReconstructSpringBone();
👍

2024-07-18 01:48 UTC, Santarh commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
> +        public void RestoreInitialTransform()
👍

2024-07-18 01:48 UTC, Santarh commented on Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBufferBuilder.cs
> +    public class FastSpringBoneBufferBuilder
このクラスの存在意義を若干疑問視しています。

そもそもとして `RestoreInitialTransform` の実装のために分割したんだと察せられるんですが
初期化によって変わるのが結局 `NativeArray<BlittableLogic> Logics` にとどまるなら、
初期化時点での `NativeArray<BlittableLogic> Logics` をコピーして保存しておくだけで良い気がします。

すると構築のための前段階の情報を保持する必要もなく、特にクラス分割の必要もないように思えます。

（このクラスがユーティリティになりきれておらずメンバ関数という状態を持っているのが今後バグを孕みそうなのが怖いというのもあるんですが…）

2024-07-18 05:00 UTC, ousttrue commented on Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBuffer.cs
> +        static Transform[] MakeFlattenTransformList(FastSpringBoneSpring[] springs)
FastSpringBoneBufferBuilder を再び FastSpringBoneBuffer.FastSpringBoneBuffer に戻し。
Index 逆引き Dict をやめて Array.IndexOf に置き換え(頻度的に読み易さ優先で)。

2024-07-18 05:01 UTC, ousttrue commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone .cs
> +            List<BlittableLogic> blittableLogics = new();
副作用の少ない、使い捨てリストに。
頻度的に読み易さ優先。
GC 対策としてのメンバー化は必要であれば。

2024-07-18 07:38 UTC, Santarh approved these changes
よさげです。
🍰 いくつか

2024-07-18 07:38 UTC, Santarh commented on Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBuffer.cs
> +                    : worldChildPosition;
なるほど、この関数を public にしないといけない理由としては
この辺で transform の現在の状態に依存する箇所があるから、ですかね。

2024-07-18 07:38 UTC, Santarh commented on Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBuffer.cs
> +        public unsafe void SyncAndZeroVelocity(IReadOnlyList<BlittableLogic> logics)
ここは unsafe 必要なさそうです

2024-07-18 07:38 UTC, Santarh commented on Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBuffer.cs
> +        static public void AddLogic(Transform[] Transforms, List<BlittableLogic> BlittableLogics, FastSpringBoneSpring spring)
public static のほうが読みやすそうです。

2024-07-18 07:38 UTC, Santarh commented on Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBuffer.cs
> +        static public void AddLogic(Transform[] Transforms, List<BlittableLogic> BlittableLogics, FastSpringBoneSpring spring)
この関数の先頭で Clear してしまって `BuildLogic` としてしまった方が分かりやすい命名になるかもです

2024-07-18 07:49 UTC, ousttrue commented on Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBuffer.cs
> +        public unsafe void SyncAndZeroVelocity(IReadOnlyList<BlittableLogic> logics)
NativeArray の indexer が要求するのです・・・

```cs
    public unsafe T this[int index]
```

2024-07-18 07:54 UTC, ousttrue commented on Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBuffer.cs
> +        static public void AddLogic(Transform[] Transforms, List<BlittableLogic> BlittableLogics, FastSpringBoneSpring spring)
ToDo: AddLogic 名前変えてもう少し整理する

`BuildLogic` とか `LogicFromTransform`。
Transform の現状から Logic の初期状態を構築するの意。

2024-07-18 07:55 UTC, ousttrue commented on Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBuffer.cs
> +        public unsafe void SyncAndZeroVelocity(IReadOnlyList<BlittableLogic> logics)
勘違い。無しで動いた・・・。

2024-07-18 08:16 UTC, ousttrue commented on Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBuffer.cs
> +        static public void AddLogic(Transform[] Transforms, List<BlittableLogic> BlittableLogics, FastSpringBoneSpring spring)
返り値を使うように少し改善

2024-07-18 09:47 UTC, merged