[SpringBone] BlittableLogic を immutable にするべく currentTail と prevTail を外出し
vrm-c/UniVRM pull request #2433
Opened 2024-09-11 12:03 UTC by ousttrue

ちょっとコード整理。

- BlittableLogic => BlittableJointInit
- BlittableJoint => BlittableJointSettings(reconstruct なしで 内容の更新をできるようにする予定)

2024-09-11 12:11 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/Blittables/BlittableJointInit.cs
> -        public Vector3 prevTail;
毎フレーム変化する currentTail と prevTail を外出しして
この型は不変情報になります。

2024-09-11 12:13 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs
> +        // 長さと index 同じ
配列を増やしたので 同じ index で並び替え。

joint 系、spring, collider, transform系 にする方針。
transformには(joint, collider, center など諸々格納の様子)

2024-09-11 12:14 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs
> +            }
dispose のエラーが出るのでメンバーの field の代入を避けた。
(simple viewer play stop でも発生)

2024-09-11 12:18 UTC, ousttrue commented on Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeSpringBone.cs
>                  transform.localRotation = m_initialLocalRotations[i];
reset 機能。一時休止。TODO

2024-09-17 03:29 UTC, notargs requested changes
主に命名などの細かい点について数点コメントしました 🙇

2024-09-17 03:29 UTC, notargs commented on Assets/UniGLTF/Runtime/SpringBoneJobs/Blittables/BlittableJointInit.cs
> +    public struct BlittableJointInit
「定数である」ことを示す名称としては「Init」はあまり適切ではない気もする。
「Constant」とかが良いかも？

2024-09-17 03:29 UTC, notargs commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs
> +            // dispose が狂う？？
ちょっとコード内のコメントの説明が足りてない感じします。後続の実装者のためにもう少し課題感と、なぜこのコードスニペットが使えないのかをしっかり書いておきたさ
（あまり明確な理由がないのならば単にコメントを削除、でもよさそう）

2024-09-17 03:29 UTC, notargs commented on Assets/UniGLTF/Runtime/SpringBoneJobs/Blittables/BlittableJointSettings.cs
> +    public struct BlittableJointSettings
「毎フレーム変化されること」を示す名称として「Setting」は適切ではなさそう（むしろSettingのほうがImmutableなイメージすらある）
「State」などがよさそう？

2024-09-17 03:29 UTC, notargs commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs
> +        public (NativeArray<Vector3> current, NativeArray<Vector3> prev, NativeArray<Vector3> next) FlipBuffer()
「Flip」という命名から期待される挙動と実際の挙動が違いそう。
一般化しづらい複雑な処理をやっており、適切な名称は何か？は少し悩ましげ。
`RotateAndGetPositionBuffers` とか…？

2024-09-17 03:47 UTC, notargs commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs
> +        public (NativeArray<Vector3> current, NativeArray<Vector3> prev, NativeArray<Vector3> next) FlipBuffer()
確保破棄とは別にSpanとして扱うなどすれば、素直にFlipが書ける気もする

2024-09-17 03:47 UTC, notargs commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs
> +        public (NativeArray<Vector3> current, NativeArray<Vector3> prev, NativeArray<Vector3> next) FlipBuffer()
ただ三要素なのでそれでもFlipと呼べるかは微妙なところ

2024-09-17 05:03 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs
> +            // dispose が狂う？？
```cs
            // dispose が狂う？？
            var tmp = _prevTails;
            _currentTails = _nextTails;
            _prevTails = _currentTails;
            _nextTails = tmp;
```

NativeArray<Vector3> をコピーして入れ替えると Dispose 時に以下の例外が発生します。

```
ObjectDisposedException: The Unity.Collections.NativeArray`1[UnityEngine.Vector3] has been deallocated, it is not allowed to access it
```

struct NativeArray のコピーには副作用(class の field の NativeArray など特定の条件で)があると推察されます。

2024-09-17 05:11 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/Blittables/BlittableJointSettings.cs
> +    public struct BlittableJointSettings
とりあえず  BlittableJointImmutable と BlittableJointIMutable に変えときました。
`Blittable` が入力設定であることを暗示しているので。

State は関数型 での `(input, currentstate)=>nextstate` に使うつもりなので Joint 設定に対しては見送り。
Verlet 積分の currentTail, prevTail, nextTail がそれにあたります(改名するか未定)。

2024-09-17 05:34 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs
> +            // dispose が狂う？？
普通にバグってました 🙏 

```cs
            var tmp = _prevTails;
            _currentTails = _nextTails;
            _prevTails = _currentTails; // _prev と _current が同じ !
            _nextTails = tmp;
// 👇
            var tmp = _prevTails;
            _prevTails = _currentTails;
            _currentTails = _nextTails;
            _nextTails = tmp;
```

2024-09-17 05:35 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs
> +        public (NativeArray<Vector3> current, NativeArray<Vector3> prev, NativeArray<Vector3> next) FlipBuffer()
TripleBuffer の Flip なので意味的には通ると思います。

DirectX の SwapChain の Flip( chain の数は N)

https://learn.microsoft.com/ja-jp/windows/win32/direct3ddxgi/dxgi-flip-model#how-to-use-dxgi-flip-model

2024-09-18 02:04 UTC, notargs requested changes
二点、追加でコメントしました。ここ以外は大丈夫そう 👍

2024-09-18 02:04 UTC, notargs commented on Assets/UniGLTF/Runtime/SpringBoneJobs/Blittables/BlittableJointImmutable.cs
> +    public struct BlittableJointImmutable
readonly structにすることでimmutableであることを型から明示できそう？

2024-09-18 02:04 UTC, notargs commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs
> +            // dispose が狂う？？
このコメントは消し忘れ？

2024-09-18 04:03 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/Blittables/BlittableJointImmutable.cs
> +    public struct BlittableJointImmutable
readonlyは readonly struct じゃなくて、こっちの readonly の方でした。

```cs
        [ReadOnly] public NativeArray<BlittableJointMutable> Joints;
        [ReadOnly] public NativeArray<BlittableJointImmutable> Logics;
```

２つにわかれているのは、ライフタイムの違い。
完全に不変という意味ではなく、変化のスコープ、変わりやすさ(再構築とEditorのスライダー)が違う。
初期姿勢と設定なので最初、 `Init` と `Setting` と名付けていた。

2024-09-18 05:30 UTC, notargs approved these changes
LGTM 👍

2024-09-18 07:08 UTC, merged