[WIP] BlittableModelLevel
vrm-c/UniVRM pull request #2454
Opened 2024-10-03 10:43 UTC by ousttrue

2024-10-04 04:45 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/Blittables/BlittableSpring.cs
> +        public int modelIndex;
ponter じゃなくて index ようにした。unsafe 不要になった。

2024-10-04 04:46 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs
> +        private Dictionary<Transform, int> _jointMap = new();
Transform から modelIndex, jointIndex を逆引きする

2024-10-04 04:47 UTC, ousttrue commented on Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs
> +                        m_root.Runtime.SpringBone.SetJointLevel(m_target.transform, m_target.Blittable);
JointLevelのSet。Reconstructは不要になった。

2024-10-04 07:37 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/UpdateFastSpringBoneJob.cs
> +                               + external * scalingFactor; // 外力による移動量
scaling によるパラメーター補正 #2420
図形的な相似になるのでこれでOK

2024-10-07 06:13 UTC, notargs requested changes
1点可読性の面でコメントしました 🙇

2024-10-07 07:41 UTC, ousttrue commented on Assets/UniGLTF/Runtime/Extensions/TransformExtensions.cs
> +        public static float AbsoluteMaxValue(in Vector3 s)
３値abs max を TransformExtensions.AbsoluteMaxValue に整理。

2024-10-07 07:42 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/UpdateFastSpringBoneJob.cs
> +            }
👉  `TransformExtensions.AbsoluteMaxValue`

2024-10-08 03:59 UTC, notargs approved these changes
LGTM

2024-10-08 04:05 UTC, merged