[export][springbone] bake 時に SpringBone と LookAt に反映する実装
vrm-c/UniVRM pull request #2468
Opened 2024-10-18 10:42 UTC by ousttrue

2024-10-21 08:43 UTC, notargs requested changes
コンフリクト修正おねがいします 🙇

2024-10-21 13:47 UTC, ousttrue commented
rebase しました 🙏

2024-10-21 13:49 UTC, ousttrue commented on Assets/VRM/Editor/Format/VRMEditorExporter.cs
> +                using (var backup = new VrmGeometryBackup(target))
using の最初に SpringBone 関連の world 位置を記録。
Dispose で復帰。

2024-10-21 13:49 UTC, ousttrue commented on Assets/VRM10/Editor/Vrm10ExportDialog.cs
> +                        using (var backup = new Vrm10GeometryBackup(root))
using の最初に SpringBone 関連の world 位置を記録。
Dispose で復帰(正規化で変わっている可能性がある)

2024-10-22 05:45 UTC, notargs approved these changes
LGTM 👍

2024-10-22 05:49 UTC, merged