[0.x][springbone] rootBone 重複対策
vrm-c/UniVRM pull request #2506
Opened 2024-11-18 05:06 UTC by ousttrue

2024-11-18 05:16 UTC, ousttrue commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +        IEnumerable<Validation> Validate()
重複 rootBones をサーチする

2024-11-18 05:18 UTC, ousttrue commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +            }
rootBone 重複にメッセージを表示

2024-11-18 05:19 UTC, ousttrue commented on Assets/VRM/Runtime/SpringBone/VRMSpringBone.cs
> +        List<Transform> RootBonesNonNullUnique
runtime 用に not null かつ unique なリスト

2024-11-18 11:58 UTC, suzuryg requested changes
ご対応ありがとうございます。1点コメントしました。

2024-11-18 16:52 UTC, ousttrue commented
Editor.OnValidate は動かなかった。
あと、ユーザーが色変更しているかもしれないので触らないことにしました。

![label](https://github.com/user-attachments/assets/64a783f9-b0e0-4a17-a1ce-3ab140b8dfb3)

2024-11-19 02:06 UTC, suzuryg requested changes
いくつかコメントしました。ご確認よろしくお願いします。

2024-11-19 02:06 UTC, suzuryg commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +            Validate();
すみません、先のコメントはユーザーがインスペクタでRootBonesを変更したときに表示が更新されてほしい、という意図でした。（そのような機能は不要？）
ここでバリデーションを行う場合、ユーザーが値を更新した後でも表示は不変です。

2024-11-19 04:01 UTC, ousttrue commented on Assets/VRM/Runtime/SpringBone/VRMSpringBone.cs
> +        public void OnValidate()
当初 `Editor.OnValidate` だったのだけど
`MonoBehaviour.OnValidate` これが正解と思われます。
rootBones 操作時もリアルタイムに反映できるようになりました。

2024-11-19 04:06 UTC, suzuryg approved these changes
LGTM👍

2024-11-19 04:06 UTC, suzuryg commented on Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs
> +            foreach (var valiation in m_target.Validations)
🍰 typo

2024-11-19 04:17 UTC, merged