[fastspringbone] InitCurrentTailsJob use spring.transformIndexOffset
vrm-c/UniVRM pull request #2507
Opened 2024-11-18 07:32 UTC by ousttrue

FastSpringBoneBufferCombiner が理解しきれていなかった。

初期化時の index ずれを修正。

2024-11-18 07:39 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs
> +            public void Execute(int springIndex)
spring 情報を使うので joint 毎ではなく spring 毎に回す

2024-11-18 07:46 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs
> +                        tailIndex= spring.transformIndexOffset + Logics[jointIndex].tailTransformIndex;
spring.transformIndexOffset が無くて index ずれがおきていた

2024-11-18 11:59 UTC, suzuryg requested changes
ご対応ありがとうございます。いくつかコメントしました。

2024-11-18 11:59 UTC, suzuryg commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs
> +            [NativeDisableParallelForRestriction] public NativeSlice<Vector3> NextTails;
`springIndex`が異なる場合は`jointIndex`も異なるため問題なし。

2024-11-18 11:59 UTC, suzuryg commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs
> +            // TODO: 速度の維持は SaveToSourceBuffer でされていたのだがデータ構造変更で場所が変わった
速度の維持は v0.128.1 で対応予定でしょうか？

2024-11-18 13:28 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs
> +            // TODO: 速度の維持は SaveToSourceBuffer でされていたのだがデータ構造変更で場所が変わった
この PR に追加します。
SaveToSourceBuffer 周りが読めてなくて機能が落ちていたので。

2024-11-19 00:38 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs
> +                buffer.RestoreCurrentTails(_currentTails, logicsOffset);
保存した CurrentTails を復帰。

2024-11-19 00:44 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs
> +                    {
CurrentTails が無い場合に NAN を使うことにしました

2024-11-19 00:45 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs
> +                    Debug.Assert(length == buffer.Logics.Length);
ついでに修正。毎回エラーになっていた

2024-11-19 00:46 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs
> +                    collider.DrawGizmo(_transforms[spring.transformIndexOffset + collider.transformIndex]);
spring.transformIndexOffset の足し忘れ。同じ問題

2024-11-19 00:49 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/InputPorts/FastSpringBoneBuffer.cs
> +                _currentTailsBackup = new(Logics.Length, Allocator.Persistent);
このバッファが未確保の場合に、
新規バッファでバックアップが無いことを判断します。

2024-11-19 00:49 UTC, ousttrue commented on Assets/UniGLTF/Runtime/SpringBoneJobs/InputPorts/FastSpringBoneBuffer.cs
> +                    currentTails.GetSubArray(offset, Logics.Length).AsSpan().Fill(new Vector3(float.NaN, float.NaN, float.NaN));
バックアップが無いので NAN を目印に投入します。

2024-11-19 02:05 UTC, suzuryg submitted a review, later dismissed
LGTM👍

2024-11-19 04:17 UTC, suzuryg approved these changes
LGTM👍

2024-11-19 04:35 UTC, merged