[vrma][editor] VRMA の EditorImport
vrm-c/UniVRM pull request #2534
Opened 2024-12-19 13:53 UTC by ousttrue

vrma 拡張子を editor import できるようにしました。

2024-12-19 13:53 UTC, ousttrue commented on Assets/VRM10/Runtime/Components/VrmAnimationInstance/Vrm10AnimationInstance.cs.meta
> +  icon: {fileID: 2800000, guid: ad4861e134018c948ac79793d290f48b, type: 3}
icon をセット

2024-12-19 14:03 UTC, ousttrue commented on Assets/VRM10/Runtime/IO/VrmAnimationImporter.cs
>      public class VrmAnimationImporter : UniGLTF.ImporterContext
Editor 向けとしては Asset 管理がいい加減だったのを改修しています

- avatar
- boxman mesh / material

など

2024-12-20 06:38 UTC, Santarh requested changes
ScriptedImporter でいくつか

2024-12-20 06:38 UTC, Santarh commented on Assets/VRM10/Editor/ScriptedImporter/VrmaScriptedImporter.cs
> +        public override void OnImportAsset(AssetImportContext context)
この関数の実装ですが
他の ScriptedImporter 実装と同じく `GltfScriptedImporterBase` を継承したら `GltfScriptedImporterBase.Import()` の呼び出しですべて済み、実装の重複もなくなりそうですが、どうでしょう？

2024-12-20 06:40 UTC, Santarh commented on Assets/VRM10/Editor/ScriptedImporter/VrmaScriptedImporter.cs
> +        public override void OnImportAsset(AssetImportContext context)
ImporterContext の実装が異なるのか。

2024-12-20 06:41 UTC, Santarh commented on Assets/VRM10/Editor/ScriptedImporter/VrmaScriptedImporter.cs
> +        public override void OnImportAsset(AssetImportContext context)
こちらは大丈夫です。

2024-12-20 06:44 UTC, Santarh approved these changes
LGTM

2024-12-20 06:51 UTC, merged