VRM1 は、XYZ_RightUpForward_RH にする
vrm-c/UniVRM pull request #727
Opened 2021-02-05 07:25 UTC by ousttrue

https://github.com/vrm-c/vrm-specification/issues/205

vrm0 は 座標変換で x, y, -z してたが、
vrm1 は 座標変換で -x, y, z する。

2021-02-10 06:52 UTC, ousttrue commented
#728 なおした。

`byteOffset = -1`

2021-02-16 08:59 UTC, Santarh requested changes
`0.x` と `1.x` で bindpose の値がおかしいのは、どこかがバグっていると思われます。

2021-02-16 09:03 UTC, Santarh commented on Assets/VRM10/Runtime/Migration/RotateY180.cs
> +                }
Here.

2021-02-16 09:27 UTC, ousttrue commented on Assets/VRM10/Runtime/Migration/RotateY180.cs
> +                }
fix to `node.scale.Length`

2021-02-19 10:57 UTC, ousttrue commented
* vrm-1.0 importer/exporter の座標変換バグ(Matrix が Z Reverse)
* Migration 周りの Matrix4x4 のバイトオーダーバグ(m01 が 16byte目になるのが正解)

を修正しました。

2021-02-19 11:02 UTC, Santarh requested changes
おつかれさまです。ヤバげな要素直接操作部分はコメントしたほうが良さそう

2021-02-19 11:02 UTC, Santarh commented on Assets/VRM10/vrmlib/Runtime/NumericsExtensions.cs
> +                ret.M41 = -ret.M41;
コメントを書いたほうが良さそう

2021-02-19 11:02 UTC, Santarh commented on Assets/VRM10/Runtime/UnityExtensions.cs
> +            var t = m.GetRow(3);
ここもできればなんらか書いておいたほうが良さそう

2021-02-19 11:02 UTC, Santarh commented on Assets/VRM10/vrmlib/Runtime/SpanLike.cs
> +                        BitConverter.ToSingle(array, start + 16),
ここも…ｗ

2021-02-19 11:18 UTC, ousttrue commented
`UnityEngine.Matrix4x4`

行ベクトル
```
Mxx, GetRow, GetCol の概念
R, R, R, 0
R, R, R, 0
R, R, R, 0
T, T, T, 1
```

メモリレイアウト
```
列優先メモリレイアウト(col0, col1, col2, col3)
 ```

これは GLTF のメモリレイアウトと同じです。

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#data-alignment

2021-02-19 11:23 UTC, Santarh approved these changes
よさそう

2021-02-19 11:23 UTC, merged